# Generated by Django 4.2.27 on 2026-01-22 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
