# Generated by Django 4.2.27 on 2026-01-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('DEPT_HEAD', 'Department Head')], default='DEPT_HEAD', max_length=20),
        ),
    ]
